const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const repo=path.resolve(process.argv[2]||'.'),target=path.join(repo,'scripts/ci-evidence.cjs'),metric=process.argv.includes('--metric');
if(!fs.existsSync(target)){console.error('Independent CI validation absent: 0/12');console.log('0');process.exit(metric?0:1);}
const api=require(target),head='a'.repeat(40),trusted='b'.repeat(40),digest=crypto.createHash('sha256').update('protected verifier').digest('hex');
const policy=()=>({repository:'owner/pilot',head,run_id:42,attempt:2,workflow:'.github/workflows/verify.yml',required_jobs:['acceptance'],protected_ref:trusted,protected_files:{'.github/workflows/verify.yml':digest,'oracle.cjs':digest},artifact:{name:'candidate',digest:'sha256:'+digest},max_age_ms:86400000});
function fixture(change=()=>{}){const p=policy(),run={id:42,run_attempt:2,repository:{full_name:p.repository},head_sha:head,path:p.workflow,workflow_id:7,status:'completed',conclusion:'success',updated_at:new Date().toISOString()},jobs={total_count:1,jobs:[{id:1,run_id:42,head_sha:head,name:'acceptance',status:'completed',conclusion:'success'}]},artifacts={total_count:1,artifacts:[{id:9,name:'candidate',expired:false,digest:'sha256:'+digest,workflow_run:{id:42,head_sha:head},created_at:new Date().toISOString(),expires_at:new Date(Date.now()+86400000).toISOString()}]};
 const state={p,run,jobs,artifacts,content:'protected verifier',error:false};change(state);let calls=[];const query=endpoint=>{calls.push(endpoint);if(state.error)throw Error('API unavailable');if(endpoint.includes('/contents/'))return{encoding:'base64',content:Buffer.from(state.content).toString('base64')};if(endpoint.includes('/jobs?'))return jobs;if(endpoint.includes('/artifacts?'))return artifacts;if(endpoint.includes('/workflows/7'))return{id:7,path:p.workflow,state:'active'};return run;};return{run:()=>api.verify(p,query),calls};}
let n=0,fail=0;function test(name,f){try{f();n++;console.error('PASS: '+name);}catch(e){fail++;console.error('FAIL: '+name+': '+e.message);}}
test('fresh independently fetched candidate passes',()=>{const f=fixture();assert.equal(f.run().head,head);assert.ok(f.calls.some(x=>x.includes('/attempts/2/jobs')));assert.ok(f.calls.some(x=>x.includes('ref='+trusted)));});
for(const [name,change] of [
 ['wrong repository',s=>s.run.repository.full_name='attacker/pilot'],['wrong head',s=>s.run.head_sha=trusted],['stale attempt',s=>s.run.run_attempt=3],['wrong workflow',s=>s.run.path='.github/workflows/untrusted.yml'],['cancelled run',s=>s.run.conclusion='cancelled'],['skipped required job',s=>s.jobs.jobs[0].conclusion='skipped'],['missing required job',s=>{s.jobs.jobs=[];s.jobs.total_count=0;}],['changed protected verifier',s=>s.content='weakened verifier'],['expired artifact',s=>s.artifacts.artifacts[0].expired=true],['old CI run',s=>s.run.updated_at='2000-01-01T00:00:00Z'],['API unavailable',s=>s.error=true]
])test(name,()=>assert.throws(fixture(change).run));
console.log(metric?n:n+'/12 independent CI checks passed');if(!metric&&fail)process.exitCode=1;
