const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(process.argv[2]||'.'),metric=process.argv.includes('--metric');
const delivery=require(path.join(root,'scripts/vercel-delivery.cjs')),release=require(path.join(root,'scripts/release-evidence.cjs')),a=require(path.join(root,'scripts/acceptance.cjs'));
if(typeof delivery.authorize!=='function'){console.log(metric?0:'Hosted owner authorization unavailable');process.exit(metric?0:1);}
let n=0,fail=0;async function test(name,fn){try{await fn();n++;console.error('PASS: '+name);}catch(e){fail++;console.error('FAIL: '+name+': '+e.message);}}
const policy={repository:'owner/pilot',environment:'pilot',deployment_branch:'master',approved_request_sha256:'b'.repeat(64),ci:{protected_ref:'a'.repeat(40)},approval:{mode:'workflow_dispatch',actor:'owner'}};
const context={GITHUB_RUN_ID:'12',GITHUB_RUN_ATTEMPT:'1',GITHUB_REPOSITORY:policy.repository,FORGE_APPROVED_REQUEST_SHA256:policy.approved_request_sha256};
const run={id:12,run_attempt:1,event:'workflow_dispatch',status:'in_progress',repository:{full_name:policy.repository,private:true},actor:{login:'owner',type:'User'},triggering_actor:{login:'owner',type:'User'},path:'.github/workflows/forge-pilot.yml',head_branch:'master',head_sha:policy.ci.protected_ref};
function read(r=run,environment={deployment_branch_policy:{protected_branches:true},protection_rules:[]},protectedBranch=true){return async route=>{if(route.includes('/environments/'))return environment;if(route.includes('/branches/'))return{protected:protectedBranch};if(route.endsWith('/actions/runs/12'))return r;throw Error('Unexpected GitHub query');};}
(async()=>{
await test('owner dispatch works without paid environment reviewers',async()=>assert.equal((await delivery.authorize(policy,read(),context)).mode,'workflow_dispatch'));
await test('unapproved event or actor cannot authorize delivery',async()=>{for(const delta of [{event:'push'},{actor:{login:'other',type:'User'}},{triggering_actor:{login:'other',type:'User'}},{actor:{login:'owner',type:'Bot'}}])await assert.rejects(()=>delivery.authorize(policy,read({...run,...delta}),context));});
await test('wrong repository branch workflow or tooling revision blocks',async()=>{for(const delta of [{repository:{full_name:'other/pilot',private:true}},{repository:{full_name:policy.repository,private:false}},{head_branch:'feature'},{path:'.github/workflows/ci.yml'},{head_sha:'c'.repeat(40)}])await assert.rejects(()=>delivery.authorize(policy,read({...run,...delta}),context));});
await test('changed request missing context or rerun identity blocks',async()=>{for(const delta of [{FORGE_APPROVED_REQUEST_SHA256:'c'.repeat(64)},{GITHUB_RUN_ID:'garbage'},{GITHUB_RUN_ATTEMPT:'2'},{GITHUB_REPOSITORY:'other/pilot'}])await assert.rejects(()=>delivery.authorize(policy,read(),{...context,...delta}));await assert.rejects(()=>delivery.authorize(policy,read({...run,status:'completed'}),context));});
await test('manual dispatch retains actual branch and environment restrictions',async()=>{await assert.rejects(()=>delivery.authorize(policy,read(run,undefined,false),context));await assert.rejects(()=>delivery.authorize(policy,read(run,{deployment_branch_policy:null,protection_rules:[]}),context));});
await test('default reviewer gate remains required and unknown mode blocks',async()=>{const p={...policy};delete p.approval;await assert.rejects(()=>delivery.authorize(p,read(),context));assert.equal((await delivery.authorize(p,read(run,{deployment_branch_policy:{protected_branches:true},protection_rules:[{type:'required_reviewers',reviewers:[{id:1}]}]}),context)).mode,'environment_reviewers');await assert.rejects(()=>delivery.authorize({...policy,approval:{mode:'disabled'}},read(),context));});
const parent=fs.realpathSync(os.tmpdir()),temp=fs.mkdtempSync(path.join(parent,'forge-hosted-')),reportFile=path.join(temp,'report.json'),oldReport=process.env.FORGE_EVAL_REPORT;
try{
  process.env.FORGE_EVAL_REPORT=reportFile;
  const required=['claude','codex'].map(agent=>({agent,platform:'win32',cli_version:'fixture',requested_model:'fixture',oracle_sha256:'d'.repeat(64),runner_sha256:'e'.repeat(64)}));
  const rows=required.map(r=>({...r,bundle_sha256:release.identity(root),installed_sha256:'f'.repeat(64),source_sha256:'f'.repeat(64),loaded_path:'/installed/forge/SKILL.md',route:'forge --classic',status:'pass',ended_at:new Date().toISOString(),transcript_sha256:'a'.repeat(64),isolation:'os-sandbox',authentication:{mode:'subscription',method:r.agent==='codex'?'chatgpt':'claude.ai'},cases:{feature:true,blocked:true,stale:true,failed:true},trace:{router:true,command:true,verification:true}}));
  const raw=JSON.stringify({version:1,evaluations:rows});fs.writeFileSync(reportFile,raw);
  const p={authentication:'subscription',evaluations:required,local_report_sha256:a.sha(raw),ci:{head:'a'.repeat(40),required_jobs:['Harness test suites','Harness Windows smoke'],protected_files:{'scripts/installed-eval.cjs':'e'.repeat(64),'evals/devops/installed-oracle.cjs':'d'.repeat(64),'scripts/release-evidence.cjs':'f'.repeat(64),'scripts/ci-evidence.cjs':'b'.repeat(64)}}};
  let reads=0;const io={ci:()=>{reads++;return{head:p.ci.head}},artifact:()=>{throw Error('Local reports must not claim a CI artifact')}};
  await test('hosted deterministic CI plus pinned local subscription proof passes',async()=>{assert.equal((await release.verify(root,p,p.ci.head,io)).evaluation_source,'local');assert.equal(reads,2);});
  await test('missing or changed local report cannot authorize release',async()=>{fs.writeFileSync(reportFile,raw+' ');await assert.rejects(()=>release.verify(root,p,p.ci.head,io));fs.unlinkSync(reportFile);await assert.rejects(()=>release.verify(root,p,p.ci.head,io));fs.writeFileSync(reportFile,raw);});
  await test('local path still rejects stale skipped and API-billed evaluations',async()=>{for(const delta of [{ended_at:'2000-01-01T00:00:00Z'},{status:'skipped'},{authentication:{mode:'api',method:'api_key'}}]){const copy=structuredClone(rows);Object.assign(copy[0],delta);const changed=JSON.stringify({version:1,evaluations:copy});fs.writeFileSync(reportFile,changed);await assert.rejects(()=>release.verify(root,{...p,local_report_sha256:a.sha(changed)},p.ci.head,io));}fs.writeFileSync(reportFile,raw);await assert.rejects(()=>release.verify(root,{...p,authentication:undefined},p.ci.head,io));});
  await test('local proof cannot replace failed required CI or changed protected runner',async()=>{await assert.rejects(()=>release.verify(root,p,p.ci.head,{ci:()=>{throw Error('Required CI job did not pass')}}));const changed=structuredClone(p);changed.ci.protected_files['scripts/installed-eval.cjs']='b'.repeat(64);await assert.rejects(()=>release.verify(root,changed,p.ci.head,io));});
}finally{if(oldReport===undefined)delete process.env.FORGE_EVAL_REPORT;else process.env.FORGE_EVAL_REPORT=oldReport;assert.equal(path.dirname(fs.realpathSync(temp)),parent);assert(path.basename(temp).startsWith('forge-hosted-'));fs.rmSync(temp,{recursive:true,force:true});}
console.log(metric?n:n+'/10 hosted CI checks passed');if(fail&&!metric)process.exitCode=1;
})().catch(e=>{console.error(e.message);process.exitCode=1});
