const assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(process.argv[2]||'.'),metric=process.argv.includes('--metric'),m=require(path.join(root,'scripts/installed-eval.cjs'));
if(typeof m.subscriptionAuth!=='function'||typeof m.cliEnvironment!=='function'){console.log(metric?0:'Subscription-only authentication controls absent');process.exit(metric?0:1);}
let count=0,failed=0;const test=(name,fn)=>{try{fn();count++;console.error('PASS: '+name);}catch(e){failed++;console.error('FAIL: '+name+': '+e.message);}};
const codex={status:0,stdout:'',stderr:'Logged in using ChatGPT\n'},claude={status:0,stdout:JSON.stringify({loggedIn:true,authMethod:'claude.ai',apiProvider:'firstParty',subscriptionType:'max'}),stderr:''};
test('both official subscription login controls pass',()=>{assert.equal(m.subscriptionAuth('codex',codex).mode,'subscription');assert.equal(m.subscriptionAuth('claude',claude).mode,'subscription');});
test('API and Console billing cannot pass as subscriptions',()=>{assert.throws(()=>m.subscriptionAuth('codex',{...codex,stderr:'Logged in using an API key'}));for(const delta of [{authMethod:'api_key'},{authMethod:'console'},{apiProvider:'bedrock'},{subscriptionType:null}])assert.throws(()=>m.subscriptionAuth('claude',{...claude,stdout:JSON.stringify({...JSON.parse(claude.stdout),...delta})}));});
test('missing malformed or failed authentication blocks',()=>{assert.throws(()=>m.subscriptionAuth('codex',{...codex,status:1}));assert.throws(()=>m.subscriptionAuth('codex',{...codex,stderr:''}));assert.throws(()=>m.subscriptionAuth('claude',{...claude,stdout:'not JSON'}));assert.throws(()=>m.subscriptionAuth('claude',{...claude,stdout:JSON.stringify({loggedIn:false})}));});
test('model and provider credentials are not inherited from the parent environment',()=>{const env=m.cliEnvironment({PATH:'tool-path',SystemRoot:'windows',ANTHROPIC_API_KEY:'canary',ANTHROPIC_AUTH_TOKEN:'canary',OPENAI_API_KEY:'canary',CODEX_API_KEY:'canary',CLAUDE_CODE_OAUTH_TOKEN:'canary',AWS_SECRET_ACCESS_KEY:'canary',ANTHROPIC_BASE_URL:'https://invalid.example'});assert.deepEqual(env,{PATH:'tool-path',SystemRoot:'windows'});});
console.log(metric?count:count+'/4 subscription authentication checks passed');if(failed&&!metric)process.exitCode=1;
