const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const repo=path.resolve(process.argv[2]||'.'),target=path.join(repo,'scripts/operational.cjs'),metric=process.argv.includes('--metric');
if(!fs.existsSync(target)){console.log('0');console.error('Rollout/recovery gate absent: 0/12');process.exit(metric?0:1);}
const o=require(target),a=require(path.join(repo,'scripts/acceptance.cjs'));let n=0,failed=0;
const p=()=>({version:1,target:'isolated',artifact:'dpl_candidate',configuration_sha256:'a'.repeat(64),pinned_at:'2026-01-01T00:00:00Z',min_samples:20,observation_ms:60000,max_error_rate:0,max_p95_ms:1500,max_exposure:0,strategy:'staged',recovery:{action:'rollback',rto_seconds:300,rpo_seconds:60,owner:'pilot-operator',next_drill_at:'2026-10-25T00:00:00Z'}});
function observation(policy){return{policy_sha256:a.sha(JSON.stringify(policy)),target:policy.target,artifact:policy.artifact,configuration_sha256:policy.configuration_sha256,exposure:0,started_at:'2026-01-01T00:01:00Z',ended_at:'2026-01-01T00:02:00Z',samples:Array.from({length:20},(_,i)=>({id:'sample-'+i,at:new Date(Date.parse('2026-01-01T00:01:00Z')+i*3000).toISOString(),ok:true,latency_ms:100}))};}
function test(name,fn){try{fn();n++;console.error('PASS: '+name);}catch(e){failed++;console.error('FAIL: '+name+': '+e.message);}}
test('known healthy samples satisfy pinned rollout',()=>{const policy=p();assert.equal(o.rollout(policy,observation(policy),Date.parse('2026-01-01T00:02:01Z')).decision,'CONTINUE');});
for(const[name,change]of[['missing telemetry',v=>v.samples=[]],['insufficient sample count',v=>v.samples.pop()],['short observation',v=>v.ended_at='2026-01-01T00:01:30Z'],['unhealthy candidate',v=>v.samples[0].ok=false],['latency threshold',v=>v.samples.forEach(x=>x.latency_ms=1600)]])test(name,()=>{const policy=p(),v=observation(policy);change(v);assert.equal(o.rollout(policy,v,Date.parse('2026-01-01T00:02:01Z')).decision,'HOLD');});
test('edited policy is rejected',()=>{const policy=p(),v=observation(policy);policy.max_error_rate=1;assert.throws(()=>o.rollout(policy,v,Date.parse('2026-01-01T00:02:01Z')));});
test('changed deployment is rejected',()=>{const policy=p(),v=observation(policy);v.artifact='dpl_other';assert.throws(()=>o.rollout(policy,v,Date.parse('2026-01-01T00:02:01Z')));});
const restore=()=>({target:'isolated',source:'branch-source',destination:'branch-restore',incident_at:'2026-01-01T00:01:00Z',started_at:'2026-01-01T00:01:00Z',usable_at:'2026-01-01T00:02:30Z',latest_restored_commit_at:'2026-01-01T00:00:30Z',integrity:{expected_count:20,actual_count:20,expected_sha256:'b'.repeat(64),actual_sha256:'b'.repeat(64)},compatibility:{old_app_new_schema:true,new_app_old_data:true},serving_artifact:'dpl_candidate'});
test('isolated restore meets RTO RPO integrity',()=>assert.equal(o.recovery(p(),restore()).decision,'RECOVERED'));
test('restore to source destination is rejected',()=>{const v=restore();v.destination=v.source;assert.throws(()=>o.recovery(p(),v));});
test('RTO RPO breaches and data loss block recovery',()=>{for(const change of[v=>v.usable_at='2026-01-01T00:10:00Z',v=>v.latest_restored_commit_at='2025-12-31T23:59:00Z',v=>v.integrity.actual_count=19]){const v=restore();change(v);assert.equal(o.recovery(p(),v).decision,'BLOCKED');}});
test('schema-incompatible rollback is rejected',()=>{const v=restore();v.compatibility.old_app_new_schema=false;assert.equal(o.recovery(p(),v).decision,'BLOCKED');});
console.log(metric?n:n+'/12 rollout/recovery checks passed');if(!metric&&failed)process.exitCode=1;
