'use strict';

// A model is never an author or co-author. aiCredit(command, cwd) tells whether a shell command
// would write such credit into history or a pull/merge request, in its own text or in a message
// file it names:
//   - an author / co-author trailer naming a Claude model, or any `*-by` trailer that carries an
//     Anthropic address
//   - the "Generated with Claude Code" footer on a line of its own, its link, or a session link
//   - a git identity (--author, user.name / user.email, GIT_AUTHOR_*) set to a model
// A person keeps their credit — `Claude Dupont <…>`, even a bare `Claude <their own address>` —
// and a disclosure line the user dictates (`Assisted-by: …`) is not authorship.
// ponytail: lexical. A message assembled by a script, or a file named through a variable, is not
// seen; the contract rule (SKILL.md) still binds there. Every quantifier below is bounded or
// cannot overlap its neighbour: a hook that times out screens nothing.

const fs = require('fs');
const os = require('os');
const path = require('path');

const MAX_MESSAGE = 1 << 20; // bytes; no commit message or merge-request description is larger

const M = '(?:claude|fable|opus|sonnet|haiku|mythos)';
const MAIL = String.raw`@anthropic\.com\b`;
const VER = String.raw`\d+(?:\.\d+){0,3}`;
// "(1M context)", "[bot]", "(Anthropic)" — a bracketed note counts only when it is model-ish
const NOTE = String.raw`[(\[](?=[^)\]\n]{0,40}(?:\d|bot|anthropic))[^)\]\n]{0,40}[)\]]`;
// a model word and at least one more model word, version or note: "Claude Fable 5.1", "claude[bot]"
const NAME = String.raw`${M}(?:[ \t-]*${NOTE}|[ \t-]+(?:${M}|code|${VER})){1,8}`;
const LINE = String.raw`(?:^|\n|\\n)`; // a real line start, or a literal \n inside printf / $'…' / JSON
const END = String.raw`[ \t]*(?:["'\r\n]|\\n|$)`;
const AUTHOR = String.raw`(?:co-)?author(?:ed-by)?[ \t]*[:=][ \t]*`;
const IDENTITY = String.raw`(?:--author[=\s]+|\buser\.(?:name|email)[=\s]+|\bGIT_(?:AUTHOR|COMMITTER)_(?:NAME|EMAIL)=)`;
const rx = text => new RegExp(text, 'i');

const CREDIT = [
  // a trailer at a line start or opening an argument (-m "…"): any key with an Anthropic address,
  // or an author key with a model's name
  rx(String.raw`(?:${LINE}[ \t]*|["'][ \t]*)(?:(?:[\w-]{1,40}-by|(?:co-)?author)[ \t]*[:=][^\n\\]{0,200}${MAIL}|${AUTHOR}${NAME}(?:[ \t]*<|${END}))`),
  // an author key and a bare model word with no address — at a line start only, so that a quoted
  // mention ('refuse "Co-Authored-By: Claude" trailers', grep -v '…') stays possible
  rx(String.raw`${LINE}[ \t]*${AUTHOR}${M}${END}`),
  // the footer, alone on its line: "Generated with Claude Code", "*Generated by Claude*"
  rx(String.raw`${LINE}[^a-z0-9\n"']{0,24}(?:generated|created|written|co-authored)\s+(?:with|by|using)[^a-z0-9\n"']{0,4}${M}(?:[ \t-]+(?:${M}|code|${VER})){0,4}[^a-z0-9\n"']{0,4}(?:["'\n]|\\n|$)`),
  // the footer's link, wherever it sits, and a session link
  rx(String.raw`\]\(https://claude\.(?:com/claude-code|ai/code)\)|https://claude\.ai/code/session[\w/-]{4,}`),
  // identity: an Anthropic address or a model's name as author; a bare model word as user.name
  rx(String.raw`${IDENTITY}["']?(?:[^\n\\"';&|]{0,200}${MAIL}|${NAME}(?:["']|\s|$))`),
  rx(String.raw`(?:\buser\.name[=\s]+|\bGIT_(?:AUTHOR|COMMITTER)_NAME=)(?:(["'])${M}[ \t]*\1|${M}(?=\s|$))`),
];

// What writes history or a pull/merge request. Read on the raw text: a stray apostrophe in an
// earlier comment must not hide the commit that follows it.
const GIT_WRITE = /\bgit\b(?:(?!\bgit\b)[^;&|()\n])*?\s(?:commit|merge|tag|notes|push|config)(?:\s|$)/;
const HOST_WRITE = /\b(?:gh|glab)(?:\.exe)?["']?\s(?:(?!\b(?:gh|glab)\b)[^;&|()\n])*?\b(?:create|edit|update|comment|note|review|merge|close|api)\b/;

const ARG = String.raw`(?:"([^"\n]+)"|'([^'\n]+)'|([^\s"'<>|;&()]+))`;
// -F msg, --file=msg, --body-file msg, $(cat msg), cat msg |, < msg
const MESSAGE_FILE = new RegExp(String.raw`(?:^|[\s(])(?:-F[ \t]*|--(?:[\w-]+-)?file(?:=|\s+)|cat\s+|<[ \t]*)` + ARG, 'g');
const WORKDIR = new RegExp(String.raw`(?:^|[\s(])(?:cd|-C)\s+` + ARG, 'g');
const named = (pattern, text) => [...text.matchAll(pattern)].map(m => m[1] || m[2] || m[3]);

// ~/x, and the Git Bash spellings native node cannot open: /c/x and /tmp/x.
function native(file) {
  const home = file.replace(/^~(?=\/|$)/, () => os.homedir());
  if (process.platform !== 'win32') return home;
  return home.replace(/^\/([A-Za-z])\//, '$1:/').replace(/^\/tmp(?=\/|$)/, () => os.tmpdir());
}

function read(file) {
  try {
    const stat = fs.statSync(file);
    return stat.isFile() && stat.size <= MAX_MESSAGE ? fs.readFileSync(file, 'utf8') : '';
  } catch {
    return '';
  }
}

function aiCredit(command, cwd) {
  const flat = command.replace(/\\\r?\n/g, ' ');
  if (!GIT_WRITE.test(flat) && !HOST_WRITE.test(flat)) return false;
  const root = typeof cwd === 'string' && cwd ? cwd : process.cwd();
  const dirs = ['.', ...named(WORKDIR, command)].map(dir => path.resolve(root, native(dir)));
  const files = named(MESSAGE_FILE, command).flatMap(file => dirs.map(dir => read(path.resolve(dir, native(file)))));
  return [command, ...files].some(text => CREDIT.some(pattern => pattern.test(text)));
}

module.exports = { aiCredit };
